import { normalizeSpeechLanguage, type SpeechLanguage } from '../utils/speechLanguage';
import { isPageHidden } from '../utils/pageVisibility';
import { CHARACTER_VOICE_REVISION, getCharacterVoice } from '../data/characterVoices';
// Character speech is generated by the server so the Gemini API key never enters the browser bundle.
const audioBufferCache = new Map<string, { buffer: AudioBuffer; playbackRate: number }>();
let activeSourceNode: AudioBufferSourceNode | null = null;
let activeRequest: AbortController | null = null;
let generation = 0;
let available: boolean | null = null;
let availabilityExpires = 0;
let retryAfter = 0;
let availabilityRequest: Promise<boolean> | null = null;

export function isGeminiTTSEnabled(): boolean {
  return localStorage.getItem('ITSME_GEMINI_TTS_ENABLED') !== 'false';
}

export function setGeminiTTSEnabled(enabled: boolean) {
  localStorage.setItem('ITSME_GEMINI_TTS_ENABLED', String(enabled));
}

export async function isGeminiVoiceAvailable(): Promise<boolean> {
  if (Date.now() < retryAfter) return false;
  if (available !== null && Date.now() < availabilityExpires) return available;
  if (!availabilityRequest) {
    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), 3000);
    availabilityRequest = fetch('/api/speech', { signal: controller.signal })
      .then(async response => {
        if (!response.ok) return false;
        const status = await response.json() as { available?: boolean };
        available = status.available === true;
        availabilityExpires = Date.now() + 60000;
        return available;
      })
      .catch(() => false)
      .finally(() => { clearTimeout(timeout); availabilityRequest = null; });
  }
  return availabilityRequest;
}

export function getCachedGeminiVoiceAvailability(): boolean | null {
  if (Date.now() < retryAfter) return false;
  return Date.now() < availabilityExpires ? available : null;
}

export function stopGeminiAudio() {
  generation += 1;
  activeRequest?.abort();
  activeRequest = null;
  if (activeSourceNode) {
    activeSourceNode.onended = null;
    try { activeSourceNode.stop(); } catch { /* already stopped */ }
    activeSourceNode.disconnect();
    activeSourceNode = null;
  }
}

export async function playGeminiSpeech(
  text: string,
  options: {
    characterId?: string;
    language?: SpeechLanguage;
    audioCtx: AudioContext;
    onStart?: () => void;
    onEnd?: () => void;
  },
): Promise<boolean> {
  if (isPageHidden() || !isGeminiTTSEnabled() || !text.trim()) return false;
  const currentGeneration = generation;
  if (!(await isGeminiVoiceAvailable()) || currentGeneration !== generation) return false;

  const cleanText = text.trim();
  const language = normalizeSpeechLanguage(options.language);
  const cacheKey = `${CHARACTER_VOICE_REVISION}:${language}:${options.characterId || 'ggomi'}:${cleanText}`;
  try {
    const ctx = options.audioCtx;
    if (ctx.state === 'suspended') {
      // Autoplay/device restrictions can leave resume() pending indefinitely.
      let resumeTimer: ReturnType<typeof setTimeout> | undefined;
      try {
        const resumed = await Promise.race([
          ctx.resume().then(() => true),
          new Promise<boolean>(resolve => { resumeTimer = setTimeout(() => resolve(false), 3000); }),
        ]);
        if (!resumed) return false;
      } finally { clearTimeout(resumeTimer); }
    }
    if (currentGeneration !== generation || isPageHidden()) return false;
    let clip = audioBufferCache.get(cacheKey);
    if (!clip) {
      const request = new AbortController();
      activeRequest = request;
      const timeout = setTimeout(() => request.abort(), 30000);
      let response: Response;
      let wav: ArrayBuffer;
      try {
        response = await fetch('/api/speech', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ text: cleanText, characterId: options.characterId || 'ggomi', language }),
          signal: request.signal,
        });
        if (response.status === 429 || response.status === 503) {
          const seconds = Number(response.headers.get('Retry-After')) || 60;
          retryAfter = Date.now() + Math.max(1, Math.min(86400, seconds)) * 1000;
        }
        if (!response.ok) throw new Error(`Speech server returned ${response.status}`);
        wav = await response.arrayBuffer();
      } finally {
        clearTimeout(timeout);
        if (activeRequest === request) activeRequest = null;
      }
      if (currentGeneration !== generation || isPageHidden()) return false;
      const buffer = await ctx.decodeAudioData(wav);
      // A small lift gives the light female fallback a younger cartoon resonance.
      // The server requests slower speech, keeping the final pace near normal.
      // Gemini's directed child performance is played unmodified.
      const playbackRate = response.headers.get('X-Speech-Provider') === 'elevenlabs'
        ? getCharacterVoice(options.characterId || 'ggomi').fallbackPlaybackRate : 1;
      clip = { buffer, playbackRate };
      if (audioBufferCache.size >= 60) audioBufferCache.delete(audioBufferCache.keys().next().value!);
      audioBufferCache.set(cacheKey, clip);
    }
    if (currentGeneration !== generation || isPageHidden()) return false;

    const sourceNode = ctx.createBufferSource();
    sourceNode.buffer = clip.buffer;
    sourceNode.playbackRate.value = clip.playbackRate;
    sourceNode.connect(ctx.destination);
    activeSourceNode = sourceNode;
    sourceNode.onended = () => {
      if (activeSourceNode !== sourceNode) return;
      activeSourceNode = null;
      sourceNode.disconnect();
      options.onEnd?.();
    };
    sourceNode.start(0);
    options.onStart?.();
    return true;
  } catch (error) {
    if (currentGeneration === generation) console.warn('AI character voice unavailable:', error);
    return false;
  }
}

export function clearGeminiAudioCache() {
  audioBufferCache.clear();
}
